name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: current

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Membuat debug.keystore statis agar aplikasi bisa langsung di-update tanpa uninstal
    - name: Generate Static Debug Keystore
      run: |
        mkdir -p app
        keytool -genkey -v -keystore app/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

    # PERBAIKAN UTAMA: Mengoper rahasia token dari GitHub Secrets ke parameter kompilasi Gradle (-P)
    - name: Build with Gradle
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: gradle assembleDebug -PGROQ_API_KEY="${{ secrets.GROQ_API_KEY }}"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AI-Pet-Buddy-Groq
        path: app/build/outputs/apk/debug/app-debug.apk
